# Generated by Django 5.2.7 on 2025-12-14 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moveinfo',
            name='group',
        ),
        migrations.AddField(
            model_name='moveinfo',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned_moveinfos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
