# Generated by Django 5.2.7 on 2025-12-14 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_task_group_task_move_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
        migrations.AddField(
            model_name='message',
            name='move_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.moveinfo'),
            preserve_default=False,
        ),
    ]
