# Generated by Django 5.2.7 on 2025-10-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_message_content_alter_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
