# Generated by Django 5.2.7 on 2025-10-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='move_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
