# Generated by Django 5.2.7 on 2025-10-26 02:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_move_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_change_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
