# Generated by Django 5.2.7 on 2025-11-03 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser_email_change_token_customuser_new_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(choices=[('内見', '内見'), ('新居の決定', '新居の決定'), ('賃貸借契約', '賃貸借契約'), ('引越し日決定', '引越し日決定'), ('引越し業者選び', '引越し業者選び'), ('現住所の賃貸契約解約の連絡', '現住所の賃貸契約解約の連絡'), ('引越し業者に依頼', '引越し業者に依頼'), ('粗大ごみの収集依頼・不用品の処分', '粗大ごみの収集依頼・不用品の処分'), ('梱包資材の準備', '梱包資材の準備'), ('その他', 'その他')], max_length=100)),
                ('custom_task', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
