# Generated by Django 5.2.7 on 2025-11-03 01:59

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_task'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', app.models.UserManager()),
            ],
        ),
    ]
