# Generated by Django 5.2.7 on 2025-11-28 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_message_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveinfo',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move_info', to='app.movegroup'),
        ),
    ]
